defaults: &settings
  version: 0.1.5
  app_name: Zazo DataProvider
  app_name_key: dataprovider

development:
  <<: *settings

test:
  <<: *settings

staging:
  <<: *settings

production:
  <<: *settings
